using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public enum EnumSalleType 
{
SALLEDESMACHINES,
JARDIN,
STOCKANIMAUX,
STOCKNOURRITURE,
STOCKENERGIE,
STOCKMATERIAUX,
SALLEDUTROUNOIR,
CUISINE,
SALLEDEMBARQUEMENT,
SALLEDESNAISSANCES
}
